apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sensuagents.sensu.k8s.sensu.io
spec:
  group: sensu.k8s.sensu.io
  names:
    kind: SensuAgent
    listKind: SensuAgentList
    plural: sensuagents
    singular: sensuagent
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SensuAgent is the Schema for the sensuagents API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SensuAgentSpec defines the desired state of SensuAgent
          properties:
            ca_certificate:
              type: string
            ca_filename:
              type: string
            image:
              maxLength: 35
              minLength: 1
              type: string
            log_level:
              type: string
            replicas:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int32
              maximum: 100
              minimum: 1
              type: integer
            sensubackend_websocket:
              maxLength: 60
              minLength: 1
              type: string
            subscriptions:
              items:
                type: string
              type: array
          required:
          - replicas
          type: object
        status:
          description: SensuAgentStatus defines the observed state of SensuAgent
          properties:
            status:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
